package com.catl.ui;

import com.catl.code.AirportInterface;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.text.NumberFormat;
import javax.swing.Timer;

public class Client extends javax.swing.JFrame {

    AirportInterface madridAirport;
    AirportInterface barcelonaAirport;

    public Client() {
        initComponents();
        try {
            madridAirport = (AirportInterface) Naming.lookup("//localhost/madridAirport");
            barcelonaAirport = (AirportInterface) Naming.lookup("//localhost/barcelonaAirport");
        } catch (Exception e) {
            System.err.println("Failed to look up RMI names.");
        }

        openMadrid1.setEnabled(false);
        openMadrid2.setEnabled(false);
        openMadrid3.setEnabled(false);
        openMadrid4.setEnabled(false);

        openBarcelona1.setEnabled(false);
        openBarcelona2.setEnabled(false);
        openBarcelona3.setEnabled(false);
        openBarcelona4.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTaxiMadrid2 = new javax.swing.JLabel();
        updaterAirwayMadrid = new javax.swing.JTextField();
        labelTaxiMadrid1 = new javax.swing.JLabel();
        updaterAirwayBarcelona = new javax.swing.JTextField();
        labelMadridAirport = new javax.swing.JLabel();
        labelBarcelonaAirport = new javax.swing.JLabel();
        labelHangarMadrid = new javax.swing.JLabel();
        labelMaintenanceMadrid = new javax.swing.JLabel();
        labelParkingAreaBarcelona = new javax.swing.JLabel();
        labelNumberPassengersMadridAirport = new javax.swing.JLabel();
        updaterMadridParking = new javax.swing.JFormattedTextField();
        labelTaxiMadrid = new javax.swing.JLabel();
        updaterMadridPassengers = new javax.swing.JFormattedTextField();
        updaterMadridHangar = new javax.swing.JFormattedTextField();
        updaterMadridMaintenance = new javax.swing.JFormattedTextField();
        updaterMadridTaxi = new javax.swing.JFormattedTextField();
        jSeparator4 = new javax.swing.JSeparator();
        labelHangarMadrid1 = new javax.swing.JLabel();
        labelMaintenanceMadrid1 = new javax.swing.JLabel();
        labelParkingAreaBarcelona1 = new javax.swing.JLabel();
        labelNumberPassengersMadridAirport2 = new javax.swing.JLabel();
        updaterBarcelonaParking = new javax.swing.JFormattedTextField();
        labelTaxiMadrid4 = new javax.swing.JLabel();
        updaterBarcelonaPassengers = new javax.swing.JFormattedTextField();
        updaterBarcelonaHangar = new javax.swing.JFormattedTextField();
        updaterBarcelonaMaintenance = new javax.swing.JFormattedTextField();
        updaterBarcelonaTaxi = new javax.swing.JFormattedTextField();
        labelTaxiMadrid3 = new javax.swing.JLabel();
        labelTaxiMadrid5 = new javax.swing.JLabel();
        labelTaxiMadrid6 = new javax.swing.JLabel();
        labelTaxiMadrid7 = new javax.swing.JLabel();
        closeMadrid1 = new javax.swing.JButton();
        openMadrid1 = new javax.swing.JButton();
        closeMadrid2 = new javax.swing.JButton();
        openMadrid2 = new javax.swing.JButton();
        closeMadrid3 = new javax.swing.JButton();
        openMadrid3 = new javax.swing.JButton();
        closeMadrid4 = new javax.swing.JButton();
        openMadrid4 = new javax.swing.JButton();
        labelTaxiMadrid8 = new javax.swing.JLabel();
        labelTaxiMadrid9 = new javax.swing.JLabel();
        labelTaxiMadrid10 = new javax.swing.JLabel();
        labelTaxiMadrid11 = new javax.swing.JLabel();
        closeBarcelona1 = new javax.swing.JButton();
        openBarcelona1 = new javax.swing.JButton();
        closeBarcelona2 = new javax.swing.JButton();
        openBarcelona2 = new javax.swing.JButton();
        closeBarcelona3 = new javax.swing.JButton();
        openBarcelona3 = new javax.swing.JButton();
        closeBarcelona4 = new javax.swing.JButton();
        openBarcelona4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTaxiMadrid2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid2.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid2.setText("Airway Madrid - Barcelona");
        labelTaxiMadrid2.setFocusable(false);
        jPanel1.add(labelTaxiMadrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 40));

        updaterAirwayMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterAirwayMadrid.setAutoscrolls(false);
        updaterAirwayMadrid.setFocusable(false);
        jPanel1.add(updaterAirwayMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1020, 30));

        labelTaxiMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid1.setText("Airway Barcelona - Madrid");
        labelTaxiMadrid1.setFocusable(false);
        jPanel1.add(labelTaxiMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 40));

        updaterAirwayBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterAirwayBarcelona.setAutoscrolls(false);
        updaterAirwayBarcelona.setFocusable(false);
        jPanel1.add(updaterAirwayBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 1020, 30));

        labelMadridAirport.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelMadridAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelMadridAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMadridAirport.setText("Madrid Airport");
        labelMadridAirport.setFocusable(false);
        labelMadridAirport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(labelMadridAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 320, 40));

        labelBarcelonaAirport.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelBarcelonaAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelBarcelonaAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBarcelonaAirport.setText("Barcelona Airport");
        labelBarcelonaAirport.setFocusable(false);
        labelBarcelonaAirport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(labelBarcelonaAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 330, 40));

        labelHangarMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelHangarMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelHangarMadrid.setText("Number of Airplanes in Hangar");
        labelHangarMadrid.setFocusable(false);
        jPanel1.add(labelHangarMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 240, 30));

        labelMaintenanceMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelMaintenanceMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMaintenanceMadrid.setText("Number of Airplanes in Maintenance");
        labelMaintenanceMadrid.setFocusable(false);
        jPanel1.add(labelMaintenanceMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        labelParkingAreaBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelParkingAreaBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelParkingAreaBarcelona.setText("Number of Airplanes in Taxi Area");
        labelParkingAreaBarcelona.setFocusable(false);
        jPanel1.add(labelParkingAreaBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 260, 30));

        labelNumberPassengersMadridAirport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelNumberPassengersMadridAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersMadridAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersMadridAirport.setText("Number of Passengers at the Airport");
        labelNumberPassengersMadridAirport.setFocusable(false);
        jPanel1.add(labelNumberPassengersMadridAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 290, 30));

        updaterMadridParking.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridParking.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridParking.setToolTipText("");
        updaterMadridParking.setFocusable(false);
        updaterMadridParking.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridParking, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 110, 40));

        labelTaxiMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid.setText("Runway 4");
        labelTaxiMadrid.setFocusable(false);
        jPanel1.add(labelTaxiMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, 30));

        updaterMadridPassengers.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridPassengers.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridPassengers.setToolTipText("");
        updaterMadridPassengers.setFocusable(false);
        updaterMadridPassengers.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridPassengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 110, 40));

        updaterMadridHangar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridHangar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridHangar.setToolTipText("");
        updaterMadridHangar.setFocusable(false);
        updaterMadridHangar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridHangar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, 40));

        updaterMadridMaintenance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridMaintenance.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridMaintenance.setToolTipText("");
        updaterMadridMaintenance.setFocusable(false);
        updaterMadridMaintenance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, 40));

        updaterMadridTaxi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridTaxi.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridTaxi.setToolTipText("");
        updaterMadridTaxi.setFocusable(false);
        updaterMadridTaxi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 110, 40));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setPreferredSize(new java.awt.Dimension(4, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 10, 430));

        labelHangarMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelHangarMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelHangarMadrid1.setText("Number of Airplanes in Hangar");
        labelHangarMadrid1.setFocusable(false);
        jPanel1.add(labelHangarMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 240, 30));

        labelMaintenanceMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelMaintenanceMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMaintenanceMadrid1.setText("Number of Airplanes in Maintenance");
        labelMaintenanceMadrid1.setFocusable(false);
        jPanel1.add(labelMaintenanceMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, 30));

        labelParkingAreaBarcelona1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelParkingAreaBarcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaBarcelona1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelParkingAreaBarcelona1.setText("Number of Airplanes in Taxi Area");
        labelParkingAreaBarcelona1.setFocusable(false);
        jPanel1.add(labelParkingAreaBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 260, 30));

        labelNumberPassengersMadridAirport2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelNumberPassengersMadridAirport2.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersMadridAirport2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersMadridAirport2.setText("Number of Passengers at the Airport");
        labelNumberPassengersMadridAirport2.setFocusable(false);
        jPanel1.add(labelNumberPassengersMadridAirport2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 290, 30));

        updaterBarcelonaParking.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaParking.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaParking.setToolTipText("");
        updaterBarcelonaParking.setFocusable(false);
        updaterBarcelonaParking.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaParking, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 110, 40));

        labelTaxiMadrid4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid4.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid4.setText("Number of Airplanes in Parking Area ");
        labelTaxiMadrid4.setFocusable(false);
        jPanel1.add(labelTaxiMadrid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, 30));

        updaterBarcelonaPassengers.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaPassengers.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaPassengers.setToolTipText("");
        updaterBarcelonaPassengers.setFocusable(false);
        updaterBarcelonaPassengers.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaPassengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 110, 40));

        updaterBarcelonaHangar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaHangar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaHangar.setToolTipText("");
        updaterBarcelonaHangar.setFocusable(false);
        updaterBarcelonaHangar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaHangar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 110, 40));

        updaterBarcelonaMaintenance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaMaintenance.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaMaintenance.setToolTipText("");
        updaterBarcelonaMaintenance.setFocusable(false);
        updaterBarcelonaMaintenance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 110, 40));

        updaterBarcelonaTaxi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaTaxi.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaTaxi.setToolTipText("");
        updaterBarcelonaTaxi.setFocusable(false);
        updaterBarcelonaTaxi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 110, 40));

        labelTaxiMadrid3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid3.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid3.setText("Number of Airplanes in Parking Area ");
        labelTaxiMadrid3.setFocusable(false);
        jPanel1.add(labelTaxiMadrid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        labelTaxiMadrid5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid5.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid5.setText("Runway 1");
        labelTaxiMadrid5.setFocusable(false);
        jPanel1.add(labelTaxiMadrid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 30));

        labelTaxiMadrid6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid6.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid6.setText("Runway 3");
        labelTaxiMadrid6.setFocusable(false);
        jPanel1.add(labelTaxiMadrid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 30));

        labelTaxiMadrid7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid7.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid7.setText("Runway 2");
        labelTaxiMadrid7.setFocusable(false);
        jPanel1.add(labelTaxiMadrid7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        closeMadrid1.setText("Close");
        closeMadrid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMadrid1MouseClicked(evt);
            }
        });
        jPanel1.add(closeMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 70, 30));

        openMadrid1.setText("Open");
        openMadrid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMadrid1MouseClicked(evt);
            }
        });
        jPanel1.add(openMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 70, 30));

        closeMadrid2.setText("Close");
        closeMadrid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMadrid2MouseClicked(evt);
            }
        });
        jPanel1.add(closeMadrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 30));

        openMadrid2.setText("Open");
        openMadrid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMadrid2MouseClicked(evt);
            }
        });
        jPanel1.add(openMadrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 70, 30));

        closeMadrid3.setText("Close");
        closeMadrid3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMadrid3MouseClicked(evt);
            }
        });
        jPanel1.add(closeMadrid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 70, 30));

        openMadrid3.setText("Open");
        openMadrid3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMadrid3MouseClicked(evt);
            }
        });
        jPanel1.add(openMadrid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 70, 30));

        closeMadrid4.setText("Close");
        closeMadrid4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMadrid4MouseClicked(evt);
            }
        });
        jPanel1.add(closeMadrid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 70, 30));

        openMadrid4.setText("Open");
        openMadrid4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMadrid4MouseClicked(evt);
            }
        });
        jPanel1.add(openMadrid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 70, 30));

        labelTaxiMadrid8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid8.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid8.setText("Runway 4");
        labelTaxiMadrid8.setFocusable(false);
        jPanel1.add(labelTaxiMadrid8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, 30));

        labelTaxiMadrid9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid9.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid9.setText("Runway 1");
        labelTaxiMadrid9.setFocusable(false);
        jPanel1.add(labelTaxiMadrid9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, 30));

        labelTaxiMadrid10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid10.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid10.setText("Runway 3");
        labelTaxiMadrid10.setFocusable(false);
        jPanel1.add(labelTaxiMadrid10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, -1, 30));

        labelTaxiMadrid11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid11.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid11.setText("Runway 2");
        labelTaxiMadrid11.setFocusable(false);
        jPanel1.add(labelTaxiMadrid11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, 30));

        closeBarcelona1.setText("Close");
        closeBarcelona1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBarcelona1MouseClicked(evt);
            }
        });
        jPanel1.add(closeBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 70, 30));

        openBarcelona1.setText("Open");
        openBarcelona1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBarcelona1MouseClicked(evt);
            }
        });
        jPanel1.add(openBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 70, 30));

        closeBarcelona2.setText("Close");
        closeBarcelona2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBarcelona2MouseClicked(evt);
            }
        });
        jPanel1.add(closeBarcelona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 70, 30));

        openBarcelona2.setText("Open");
        openBarcelona2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBarcelona2MouseClicked(evt);
            }
        });
        jPanel1.add(openBarcelona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 70, 30));

        closeBarcelona3.setText("Close");
        closeBarcelona3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBarcelona3MouseClicked(evt);
            }
        });
        jPanel1.add(closeBarcelona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 70, 30));

        openBarcelona3.setText("Open");
        openBarcelona3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBarcelona3MouseClicked(evt);
            }
        });
        jPanel1.add(openBarcelona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 70, 30));

        closeBarcelona4.setText("Close");
        closeBarcelona4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBarcelona4MouseClicked(evt);
            }
        });
        jPanel1.add(closeBarcelona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 70, 30));

        openBarcelona4.setText("Open");
        openBarcelona4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBarcelona4MouseClicked(evt);
            }
        });
        jPanel1.add(openBarcelona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMadrid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMadrid1MouseClicked
        try {
            madridAirport.closeRunway(0);
            closeMadrid1.setEnabled(false);
            openMadrid1.setEnabled(true);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_closeMadrid1MouseClicked

    private void openMadrid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMadrid1MouseClicked
        try {
            madridAirport.openRunway(0);
            closeMadrid1.setEnabled(true);
            openMadrid1.setEnabled(false);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_openMadrid1MouseClicked

    private void closeMadrid2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMadrid2MouseClicked
        try {
            madridAirport.closeRunway(1);
            closeMadrid2.setEnabled(false);
            openMadrid2.setEnabled(true);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_closeMadrid2MouseClicked

    private void openMadrid2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMadrid2MouseClicked
        try {
            madridAirport.openRunway(1);
            closeMadrid2.setEnabled(true);
            openMadrid2.setEnabled(false);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_openMadrid2MouseClicked

    private void closeMadrid3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMadrid3MouseClicked
        try {
            madridAirport.closeRunway(2);
            closeMadrid3.setEnabled(false);
            openMadrid3.setEnabled(true);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_closeMadrid3MouseClicked

    private void openMadrid3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMadrid3MouseClicked
        try {
            madridAirport.openRunway(2);
            closeMadrid3.setEnabled(true);
            openMadrid3.setEnabled(false);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_openMadrid3MouseClicked

    private void closeMadrid4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMadrid4MouseClicked
        try {
            madridAirport.closeRunway(3);
            closeMadrid4.setEnabled(false);
            openMadrid4.setEnabled(true);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_closeMadrid4MouseClicked

    private void openMadrid4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMadrid4MouseClicked
        try {
            madridAirport.openRunway(3);
            closeMadrid4.setEnabled(true);
            openMadrid4.setEnabled(false);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_openMadrid4MouseClicked

    private void closeBarcelona1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBarcelona1MouseClicked
        try {
            barcelonaAirport.closeRunway(0);
            closeBarcelona1.setEnabled(false);
            openBarcelona1.setEnabled(true);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_closeBarcelona1MouseClicked

    private void openBarcelona1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBarcelona1MouseClicked
        try {
            barcelonaAirport.openRunway(0);
            closeBarcelona1.setEnabled(true);
            openBarcelona1.setEnabled(false);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_openBarcelona1MouseClicked

    private void closeBarcelona2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBarcelona2MouseClicked
        try {
            barcelonaAirport.closeRunway(1);
            closeBarcelona2.setEnabled(false);
            openBarcelona2.setEnabled(true);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_closeBarcelona2MouseClicked

    private void openBarcelona2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBarcelona2MouseClicked
        try {
            barcelonaAirport.openRunway(1);
            closeBarcelona2.setEnabled(true);
            openBarcelona2.setEnabled(false);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_openBarcelona2MouseClicked

    private void closeBarcelona3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBarcelona3MouseClicked
        try {
            barcelonaAirport.closeRunway(2);
            closeBarcelona3.setEnabled(false);
            openBarcelona3.setEnabled(true);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_closeBarcelona3MouseClicked

    private void openBarcelona3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBarcelona3MouseClicked
        try {
            barcelonaAirport.openRunway(2);
            closeBarcelona3.setEnabled(true);
            openBarcelona3.setEnabled(false);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_openBarcelona3MouseClicked

    private void closeBarcelona4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBarcelona4MouseClicked
        try {
            barcelonaAirport.closeRunway(3);
            closeBarcelona4.setEnabled(false);
            openBarcelona4.setEnabled(true);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_closeBarcelona4MouseClicked

    private void openBarcelona4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBarcelona4MouseClicked
        try {
            barcelonaAirport.openRunway(3);
            closeBarcelona4.setEnabled(true);
            openBarcelona4.setEnabled(false);
        } catch (RemoteException e) {
        }
    }//GEN-LAST:event_openBarcelona4MouseClicked
    public void startClient() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Make the UserInterface visible.
                    setVisible(true);

                    // Closes the program gracefully.
                    setDefaultCloseOperation(UserInterface.EXIT_ON_CLOSE);
                    
                    // Perform periodic updates on the JLabel using SwingUtilities.invokeLater()
                    Timer timer = new Timer(20, e -> {
                        try {
                            update();
                        } catch (Exception a) {
                        }
                    });

                    timer.start();
                } catch (Exception e) {

                }
            }
        });
    }

    public void update() throws RemoteException {
        setMadridCurrentPassengers();
        setMadridHangar();
        setMadridMaintenance();
        setMadridTaxi();
        setMadridParking();

        setBarcelonaCurrentPassengers();
        setBarcelonaHangar();
        setBarcelonaMaintenance();
        setBarcelonaTaxi();
        setBarcelonaParking();

        setMadridBarcelonaAirway();
        setBarcelonaMadridAirway();

    }

    private void setMadridCurrentPassengers() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumPassengers());
        updaterMadridPassengers.setText(formattedNumber);
    }

    private void setMadridHangar() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumAirplanesInHangar());
        updaterMadridHangar.setText(formattedNumber);
    }

    private void setMadridMaintenance() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumAirplanesInMaintenance());
        updaterMadridMaintenance.setText(formattedNumber);
    }

    private void setMadridTaxi() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumAirplanesInTaxi());
        updaterMadridTaxi.setText(formattedNumber);
    }

    private void setMadridParking() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumAirplanesInParking());
        updaterMadridParking.setText(formattedNumber);
    }

    private void setBarcelonaCurrentPassengers() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumPassengers());
        updaterBarcelonaPassengers.setText(formattedNumber);
    }

    private void setBarcelonaHangar() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumAirplanesInHangar());
        updaterBarcelonaHangar.setText(formattedNumber);
    }

    private void setBarcelonaMaintenance() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumAirplanesInMaintenance());
        updaterBarcelonaMaintenance.setText(formattedNumber);
    }

    private void setBarcelonaTaxi() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumAirplanesInTaxi());
        updaterBarcelonaTaxi.setText(formattedNumber);
    }

    private void setBarcelonaParking() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumAirplanesInParking());
        updaterBarcelonaParking.setText(formattedNumber);
    }

    private void setMadridBarcelonaAirway() throws RemoteException {
        updaterAirwayMadrid.setText(madridAirport.airwayStatus());
    }

    private void setBarcelonaMadridAirway() throws RemoteException {
        updaterAirwayBarcelona.setText(barcelonaAirport.airwayStatus());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBarcelona1;
    private javax.swing.JButton closeBarcelona2;
    private javax.swing.JButton closeBarcelona3;
    private javax.swing.JButton closeBarcelona4;
    private javax.swing.JButton closeMadrid1;
    private javax.swing.JButton closeMadrid2;
    private javax.swing.JButton closeMadrid3;
    private javax.swing.JButton closeMadrid4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelBarcelonaAirport;
    private javax.swing.JLabel labelHangarMadrid;
    private javax.swing.JLabel labelHangarMadrid1;
    private javax.swing.JLabel labelMadridAirport;
    private javax.swing.JLabel labelMaintenanceMadrid;
    private javax.swing.JLabel labelMaintenanceMadrid1;
    private javax.swing.JLabel labelNumberPassengersMadridAirport;
    private javax.swing.JLabel labelNumberPassengersMadridAirport2;
    private javax.swing.JLabel labelParkingAreaBarcelona;
    private javax.swing.JLabel labelParkingAreaBarcelona1;
    private javax.swing.JLabel labelTaxiMadrid;
    private javax.swing.JLabel labelTaxiMadrid1;
    private javax.swing.JLabel labelTaxiMadrid10;
    private javax.swing.JLabel labelTaxiMadrid11;
    private javax.swing.JLabel labelTaxiMadrid2;
    private javax.swing.JLabel labelTaxiMadrid3;
    private javax.swing.JLabel labelTaxiMadrid4;
    private javax.swing.JLabel labelTaxiMadrid5;
    private javax.swing.JLabel labelTaxiMadrid6;
    private javax.swing.JLabel labelTaxiMadrid7;
    private javax.swing.JLabel labelTaxiMadrid8;
    private javax.swing.JLabel labelTaxiMadrid9;
    private javax.swing.JButton openBarcelona1;
    private javax.swing.JButton openBarcelona2;
    private javax.swing.JButton openBarcelona3;
    private javax.swing.JButton openBarcelona4;
    private javax.swing.JButton openMadrid1;
    private javax.swing.JButton openMadrid2;
    private javax.swing.JButton openMadrid3;
    private javax.swing.JButton openMadrid4;
    private javax.swing.JTextField updaterAirwayBarcelona;
    private javax.swing.JTextField updaterAirwayMadrid;
    private javax.swing.JFormattedTextField updaterBarcelonaHangar;
    private javax.swing.JFormattedTextField updaterBarcelonaMaintenance;
    private javax.swing.JFormattedTextField updaterBarcelonaParking;
    private javax.swing.JFormattedTextField updaterBarcelonaPassengers;
    private javax.swing.JFormattedTextField updaterBarcelonaTaxi;
    private javax.swing.JFormattedTextField updaterMadridHangar;
    private javax.swing.JFormattedTextField updaterMadridMaintenance;
    private javax.swing.JFormattedTextField updaterMadridParking;
    private javax.swing.JFormattedTextField updaterMadridPassengers;
    private javax.swing.JFormattedTextField updaterMadridTaxi;
    // End of variables declaration//GEN-END:variables

}
