package com.catl.ui;

import com.catl.code.AirportInterface;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.text.NumberFormat;
import javax.swing.Timer;

public class Client extends javax.swing.JFrame {

    AirportInterface madridAirport;
    AirportInterface barcelonaAirport;

    public Client() {
        initComponents();
        try {
            madridAirport = (AirportInterface) Naming.lookup("//localhost/madridAirport");
            barcelonaAirport = (AirportInterface) Naming.lookup("//localhost/barcelonaAirport");
        } catch (Exception e) {
            System.err.println("Failed to look up RMI names.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTaxiMadrid2 = new javax.swing.JLabel();
        updaterAirwayMadrid = new javax.swing.JTextField();
        labelTaxiMadrid1 = new javax.swing.JLabel();
        updaterAirwayBarcelona = new javax.swing.JTextField();
        labelMadridAirport = new javax.swing.JLabel();
        labelBarcelonaAirport = new javax.swing.JLabel();
        labelHangarMadrid = new javax.swing.JLabel();
        labelMaintenanceMadrid = new javax.swing.JLabel();
        labelParkingAreaBarcelona = new javax.swing.JLabel();
        labelNumberPassengersMadridAirport = new javax.swing.JLabel();
        updaterMadridParking = new javax.swing.JFormattedTextField();
        labelTaxiMadrid = new javax.swing.JLabel();
        updaterMadridPassengers = new javax.swing.JFormattedTextField();
        updaterMadridHangar = new javax.swing.JFormattedTextField();
        updaterMadridMaintenance = new javax.swing.JFormattedTextField();
        updaterMadridTaxi = new javax.swing.JFormattedTextField();
        jSeparator4 = new javax.swing.JSeparator();
        labelHangarMadrid1 = new javax.swing.JLabel();
        labelMaintenanceMadrid1 = new javax.swing.JLabel();
        labelParkingAreaBarcelona1 = new javax.swing.JLabel();
        labelNumberPassengersMadridAirport2 = new javax.swing.JLabel();
        updaterBarcelonaParking = new javax.swing.JFormattedTextField();
        labelTaxiMadrid4 = new javax.swing.JLabel();
        updaterBarcelonaPassengers = new javax.swing.JFormattedTextField();
        updaterBarcelonaHangar = new javax.swing.JFormattedTextField();
        updaterBarcelonaMaintenance = new javax.swing.JFormattedTextField();
        updaterBarcelonaTaxi = new javax.swing.JFormattedTextField();
        labelTaxiMadrid3 = new javax.swing.JLabel();
        labelTaxiMadrid5 = new javax.swing.JLabel();
        labelTaxiMadrid6 = new javax.swing.JLabel();
        labelTaxiMadrid7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        labelTaxiMadrid8 = new javax.swing.JLabel();
        labelTaxiMadrid9 = new javax.swing.JLabel();
        labelTaxiMadrid10 = new javax.swing.JLabel();
        labelTaxiMadrid11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTaxiMadrid2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid2.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid2.setText("Airway Madrid - Barcelona");
        labelTaxiMadrid2.setFocusable(false);
        jPanel1.add(labelTaxiMadrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 40));

        updaterAirwayMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterAirwayMadrid.setAutoscrolls(false);
        updaterAirwayMadrid.setFocusable(false);
        jPanel1.add(updaterAirwayMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1020, 30));

        labelTaxiMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid1.setText("Airway Barcelona - Madrid");
        labelTaxiMadrid1.setFocusable(false);
        jPanel1.add(labelTaxiMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 40));

        updaterAirwayBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterAirwayBarcelona.setAutoscrolls(false);
        updaterAirwayBarcelona.setFocusable(false);
        jPanel1.add(updaterAirwayBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 1020, 30));

        labelMadridAirport.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelMadridAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelMadridAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMadridAirport.setText("Madrid Airport");
        labelMadridAirport.setFocusable(false);
        labelMadridAirport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(labelMadridAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 320, 40));

        labelBarcelonaAirport.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelBarcelonaAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelBarcelonaAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBarcelonaAirport.setText("Barcelona Airport");
        labelBarcelonaAirport.setFocusable(false);
        labelBarcelonaAirport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(labelBarcelonaAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 330, 40));

        labelHangarMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelHangarMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelHangarMadrid.setText("Number of Airplanes in Hangar");
        labelHangarMadrid.setFocusable(false);
        jPanel1.add(labelHangarMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 240, 30));

        labelMaintenanceMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelMaintenanceMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMaintenanceMadrid.setText("Number of Airplanes in Maintenance");
        labelMaintenanceMadrid.setFocusable(false);
        jPanel1.add(labelMaintenanceMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        labelParkingAreaBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelParkingAreaBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelParkingAreaBarcelona.setText("Number of Airplanes in Taxi Area");
        labelParkingAreaBarcelona.setFocusable(false);
        jPanel1.add(labelParkingAreaBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 260, 30));

        labelNumberPassengersMadridAirport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelNumberPassengersMadridAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersMadridAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersMadridAirport.setText("Number of Passengers at the Airport");
        labelNumberPassengersMadridAirport.setFocusable(false);
        jPanel1.add(labelNumberPassengersMadridAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 290, 30));

        updaterMadridParking.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridParking.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridParking.setToolTipText("");
        updaterMadridParking.setFocusable(false);
        updaterMadridParking.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridParking, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 110, 40));

        labelTaxiMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid.setText("Runway 4");
        labelTaxiMadrid.setFocusable(false);
        jPanel1.add(labelTaxiMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, 30));

        updaterMadridPassengers.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridPassengers.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridPassengers.setToolTipText("");
        updaterMadridPassengers.setFocusable(false);
        updaterMadridPassengers.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridPassengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 110, 40));

        updaterMadridHangar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridHangar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridHangar.setToolTipText("");
        updaterMadridHangar.setFocusable(false);
        updaterMadridHangar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridHangar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, 40));

        updaterMadridMaintenance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridMaintenance.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridMaintenance.setToolTipText("");
        updaterMadridMaintenance.setFocusable(false);
        updaterMadridMaintenance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, 40));

        updaterMadridTaxi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridTaxi.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridTaxi.setToolTipText("");
        updaterMadridTaxi.setFocusable(false);
        updaterMadridTaxi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterMadridTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 110, 40));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setPreferredSize(new java.awt.Dimension(4, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 10, 430));

        labelHangarMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelHangarMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelHangarMadrid1.setText("Number of Airplanes in Hangar");
        labelHangarMadrid1.setFocusable(false);
        jPanel1.add(labelHangarMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 240, 30));

        labelMaintenanceMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelMaintenanceMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMaintenanceMadrid1.setText("Number of Airplanes in Maintenance");
        labelMaintenanceMadrid1.setFocusable(false);
        jPanel1.add(labelMaintenanceMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, 30));

        labelParkingAreaBarcelona1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelParkingAreaBarcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaBarcelona1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelParkingAreaBarcelona1.setText("Number of Airplanes in Taxi Area");
        labelParkingAreaBarcelona1.setFocusable(false);
        jPanel1.add(labelParkingAreaBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 260, 30));

        labelNumberPassengersMadridAirport2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelNumberPassengersMadridAirport2.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersMadridAirport2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersMadridAirport2.setText("Number of Passengers at the Airport");
        labelNumberPassengersMadridAirport2.setFocusable(false);
        jPanel1.add(labelNumberPassengersMadridAirport2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 290, 30));

        updaterBarcelonaParking.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaParking.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaParking.setToolTipText("");
        updaterBarcelonaParking.setFocusable(false);
        updaterBarcelonaParking.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaParking, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 110, 40));

        labelTaxiMadrid4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid4.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid4.setText("Number of Airplanes in Parking Area ");
        labelTaxiMadrid4.setFocusable(false);
        jPanel1.add(labelTaxiMadrid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, 30));

        updaterBarcelonaPassengers.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaPassengers.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaPassengers.setToolTipText("");
        updaterBarcelonaPassengers.setFocusable(false);
        updaterBarcelonaPassengers.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaPassengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 110, 40));

        updaterBarcelonaHangar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaHangar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaHangar.setToolTipText("");
        updaterBarcelonaHangar.setFocusable(false);
        updaterBarcelonaHangar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaHangar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 110, 40));

        updaterBarcelonaMaintenance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaMaintenance.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaMaintenance.setToolTipText("");
        updaterBarcelonaMaintenance.setFocusable(false);
        updaterBarcelonaMaintenance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 110, 40));

        updaterBarcelonaTaxi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaTaxi.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaTaxi.setToolTipText("");
        updaterBarcelonaTaxi.setFocusable(false);
        updaterBarcelonaTaxi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(updaterBarcelonaTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 110, 40));

        labelTaxiMadrid3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid3.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid3.setText("Number of Airplanes in Parking Area ");
        labelTaxiMadrid3.setFocusable(false);
        jPanel1.add(labelTaxiMadrid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        labelTaxiMadrid5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid5.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid5.setText("Runway 1");
        labelTaxiMadrid5.setFocusable(false);
        jPanel1.add(labelTaxiMadrid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 30));

        labelTaxiMadrid6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid6.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid6.setText("Runway 3");
        labelTaxiMadrid6.setFocusable(false);
        jPanel1.add(labelTaxiMadrid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 30));

        labelTaxiMadrid7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid7.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid7.setText("Runway 2");
        labelTaxiMadrid7.setFocusable(false);
        jPanel1.add(labelTaxiMadrid7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        jButton1.setText("Close");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 70, 30));

        jButton2.setText("Open");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 70, 30));

        jButton3.setText("Close");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 30));

        jButton4.setText("Open");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 70, 30));

        jButton5.setText("Close");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 70, 30));

        jButton6.setText("Open");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 70, 30));

        jButton7.setText("Close");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 70, 30));

        jButton8.setText("Open");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 70, 30));

        labelTaxiMadrid8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid8.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid8.setText("Runway 4");
        labelTaxiMadrid8.setFocusable(false);
        jPanel1.add(labelTaxiMadrid8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, 30));

        labelTaxiMadrid9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid9.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid9.setText("Runway 1");
        labelTaxiMadrid9.setFocusable(false);
        jPanel1.add(labelTaxiMadrid9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, 30));

        labelTaxiMadrid10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid10.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid10.setText("Runway 3");
        labelTaxiMadrid10.setFocusable(false);
        jPanel1.add(labelTaxiMadrid10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, -1, 30));

        labelTaxiMadrid11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelTaxiMadrid11.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid11.setText("Runway 2");
        labelTaxiMadrid11.setFocusable(false);
        jPanel1.add(labelTaxiMadrid11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, 30));

        jButton9.setText("Close");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 70, 30));

        jButton10.setText("Open");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 70, 30));

        jButton11.setText("Close");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 70, 30));

        jButton12.setText("Open");
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 70, 30));

        jButton13.setText("Close");
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 70, 30));

        jButton14.setText("Open");
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 70, 30));

        jButton15.setText("Close");
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 70, 30));

        jButton16.setText("Open");
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void startClient() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Make the UserInterface visible.
                    setVisible(true);
                    // Perform periodic updates on the JLabel using SwingUtilities.invokeLater()
                    Timer timer = new Timer(20, e -> {
                        try {
                            update();
                        } catch (Exception a) {
                        }
                    });

                    timer.start();

                    // Closes the program gracefully.
                    setDefaultCloseOperation(UserInterface.EXIT_ON_CLOSE);
                } catch (Exception e) {

                }
            }
        });
    }

    public void update() throws RemoteException {
        System.out.println("BRUH");
        setMadridCurrentPassengers();
        setMadridHangar();
        setMadridMaintenance();
        setMadridTaxi();
        setMadridParking();

        setBarcelonaCurrentPassengers();
        setBarcelonaHangar();
        setBarcelonaMaintenance();
        setBarcelonaTaxi();
        setBarcelonaParking();

        setMadridBarcelonaAirway();
        setBarcelonaMadridAirway();

    }

    private void setMadridCurrentPassengers() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumPassengers());
        updaterMadridPassengers.setText(formattedNumber);
    }

    private void setMadridHangar() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumAirplanesInHangar());
        updaterMadridHangar.setText(formattedNumber);
    }

    private void setMadridMaintenance() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumAirplanesInMaintenance());
        updaterMadridMaintenance.setText(formattedNumber);
    }

    private void setMadridTaxi() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumAirplanesInTaxi());
        updaterMadridTaxi.setText(formattedNumber);
    }

    private void setMadridParking() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(madridAirport.getNumAirplanesInParking());
        updaterMadridParking.setText(formattedNumber);
    }

    private void setBarcelonaCurrentPassengers() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumPassengers());
        updaterBarcelonaPassengers.setText(formattedNumber);
    }

    private void setBarcelonaHangar() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumAirplanesInHangar());
        updaterBarcelonaHangar.setText(formattedNumber);
    }

    private void setBarcelonaMaintenance() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumAirplanesInMaintenance());
        updaterBarcelonaMaintenance.setText(formattedNumber);
    }

    private void setBarcelonaTaxi() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumAirplanesInTaxi());
        updaterBarcelonaTaxi.setText(formattedNumber);
    }

    private void setBarcelonaParking() throws RemoteException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance();
        String formattedNumber = numberFormat.format(barcelonaAirport.getNumAirplanesInParking());
        updaterBarcelonaParking.setText(formattedNumber);
    }

    private void setMadridBarcelonaAirway() throws RemoteException {
        updaterAirwayMadrid.setText(madridAirport.airwayStatus());
    }

    private void setBarcelonaMadridAirway() throws RemoteException {
        updaterAirwayBarcelona.setText(barcelonaAirport.airwayStatus());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelBarcelonaAirport;
    private javax.swing.JLabel labelHangarMadrid;
    private javax.swing.JLabel labelHangarMadrid1;
    private javax.swing.JLabel labelMadridAirport;
    private javax.swing.JLabel labelMaintenanceMadrid;
    private javax.swing.JLabel labelMaintenanceMadrid1;
    private javax.swing.JLabel labelNumberPassengersMadridAirport;
    private javax.swing.JLabel labelNumberPassengersMadridAirport2;
    private javax.swing.JLabel labelParkingAreaBarcelona;
    private javax.swing.JLabel labelParkingAreaBarcelona1;
    private javax.swing.JLabel labelTaxiMadrid;
    private javax.swing.JLabel labelTaxiMadrid1;
    private javax.swing.JLabel labelTaxiMadrid10;
    private javax.swing.JLabel labelTaxiMadrid11;
    private javax.swing.JLabel labelTaxiMadrid2;
    private javax.swing.JLabel labelTaxiMadrid3;
    private javax.swing.JLabel labelTaxiMadrid4;
    private javax.swing.JLabel labelTaxiMadrid5;
    private javax.swing.JLabel labelTaxiMadrid6;
    private javax.swing.JLabel labelTaxiMadrid7;
    private javax.swing.JLabel labelTaxiMadrid8;
    private javax.swing.JLabel labelTaxiMadrid9;
    private javax.swing.JTextField updaterAirwayBarcelona;
    private javax.swing.JTextField updaterAirwayMadrid;
    private javax.swing.JFormattedTextField updaterBarcelonaHangar;
    private javax.swing.JFormattedTextField updaterBarcelonaMaintenance;
    private javax.swing.JFormattedTextField updaterBarcelonaParking;
    private javax.swing.JFormattedTextField updaterBarcelonaPassengers;
    private javax.swing.JFormattedTextField updaterBarcelonaTaxi;
    private javax.swing.JFormattedTextField updaterMadridHangar;
    private javax.swing.JFormattedTextField updaterMadridMaintenance;
    private javax.swing.JFormattedTextField updaterMadridParking;
    private javax.swing.JFormattedTextField updaterMadridPassengers;
    private javax.swing.JFormattedTextField updaterMadridTaxi;
    // End of variables declaration//GEN-END:variables

}
