// Package declaration.
package com.catl.ui;

// Importing classes.
import javax.swing.*;
import com.catl.code.Airport;
import java.text.NumberFormat;
import com.catl.code.BoardingGate;
import com.catl.code.PauseControl;

// User Interface class.
public class UserInterface extends javax.swing.JFrame {

    private Airport madridAirport;
    private Airport barcelonaAirport;
    private final PauseControl pauseControl;
    private volatile boolean isPaused = false;

    // UserInterface class constructor.
    public UserInterface(Airport madridAirport, Airport barcelonaAirport, PauseControl pauseControl) {
        initComponents();
        this.madridAirport = madridAirport;
        this.barcelonaAirport = barcelonaAirport;
        this.pauseControl = pauseControl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        resumeButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        labelMadridAirport = new javax.swing.JLabel();
        labelBarcelonaAirport = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        labelBusTransfersAirportBarcelona = new javax.swing.JLabel();
        labelParkingAreaBarcelona = new javax.swing.JLabel();
        labelMaintenanceMadrid = new javax.swing.JLabel();
        labelHangarMadrid = new javax.swing.JLabel();
        labelGate1Madrid = new javax.swing.JLabel();
        labelGate2Madrid = new javax.swing.JLabel();
        labelGate3Madrid = new javax.swing.JLabel();
        labelGate4Madrid = new javax.swing.JLabel();
        labelGate5Madrid = new javax.swing.JLabel();
        labelGate6Madrid = new javax.swing.JLabel();
        labelGate1Barcelona = new javax.swing.JLabel();
        labelGate2Barcelona = new javax.swing.JLabel();
        labelGate3Barcelona = new javax.swing.JLabel();
        labelGate4Barcelona = new javax.swing.JLabel();
        labelGate5Barcelona = new javax.swing.JLabel();
        labelGate6Barcelona = new javax.swing.JLabel();
        updaterBusToDowntownBarcelona = new javax.swing.JTextField();
        updaterBarcelonaCurrentPassengers = new javax.swing.JFormattedTextField();
        updaterMadridCurrentPassengers = new javax.swing.JFormattedTextField();
        labelNumberPassengersMadridAirport = new javax.swing.JLabel();
        labelNumberPassengersBarcelonaAirport = new javax.swing.JLabel();
        updaterGate6Madrid = new javax.swing.JTextField();
        updaterGate5Madrid = new javax.swing.JTextField();
        updaterGate4Madrid = new javax.swing.JTextField();
        updaterGate3Madrid = new javax.swing.JTextField();
        updaterGate2Madrid = new javax.swing.JTextField();
        updaterGate1Madrid = new javax.swing.JTextField();
        updaterGate1Barcelona = new javax.swing.JTextField();
        updaterGate2Barcelona = new javax.swing.JTextField();
        updaterGate3Barcelona = new javax.swing.JTextField();
        updaterGate4Barcelona = new javax.swing.JTextField();
        updaterGate5Barcelona = new javax.swing.JTextField();
        updaterGate6Barcelona = new javax.swing.JTextField();
        labelBusTransfersDowntownBarcelona = new javax.swing.JLabel();
        updaterBusToAirportBarcelona = new javax.swing.JTextField();
        labelBusTransfersAirportMadrid = new javax.swing.JLabel();
        labelBusTransfersDowntownMadrid = new javax.swing.JLabel();
        updaterBusToAirportMadrid = new javax.swing.JTextField();
        updaterBusToDowntownMadrid = new javax.swing.JTextField();
        updaterParkingAreaMadrid = new javax.swing.JTextField();
        updaterHangarMadrid = new javax.swing.JTextField();
        updaterMaintenanceMadrid = new javax.swing.JTextField();
        updaterParkingAreaBarcelona = new javax.swing.JTextField();
        updaterMaintenanceBarcelona = new javax.swing.JTextField();
        labelMaintenanceMadrid1 = new javax.swing.JLabel();
        labelParkingAreaBarcelona1 = new javax.swing.JLabel();
        labelHangarMadrid1 = new javax.swing.JLabel();
        updaterHangarBarcleona = new javax.swing.JTextField();
        labelTaxiMadrid = new javax.swing.JLabel();
        updaterTaxiMadrid = new javax.swing.JTextField();
        labelTaxiBarcelona = new javax.swing.JLabel();
        updaterTaxiBarcelona = new javax.swing.JTextField();
        updaterAirwayBarcelona = new javax.swing.JTextField();
        updaterAirwayMadrid = new javax.swing.JTextField();
        labelTaxiMadrid1 = new javax.swing.JLabel();
        labelTaxiMadrid2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelGate1Madrid1 = new javax.swing.JLabel();
        labelGate2Madrid1 = new javax.swing.JLabel();
        updaterGate2Madrid1 = new javax.swing.JTextField();
        labelGate4Madrid1 = new javax.swing.JLabel();
        labelGate4Madrid2 = new javax.swing.JLabel();
        updaterGate1Madrid2 = new javax.swing.JTextField();
        updaterGate1Madrid3 = new javax.swing.JTextField();
        updaterGate1Madrid4 = new javax.swing.JTextField();
        labelGate1Madrid2 = new javax.swing.JLabel();
        labelGate2Madrid2 = new javax.swing.JLabel();
        updaterGate2Madrid2 = new javax.swing.JTextField();
        labelGate4Madrid3 = new javax.swing.JLabel();
        labelGate4Madrid4 = new javax.swing.JLabel();
        updaterGate1Madrid5 = new javax.swing.JTextField();
        updaterGate1Madrid6 = new javax.swing.JTextField();
        updaterGate1Madrid7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(30, 30, 30));
        Panel.setName("Airport Simulator"); // NOI18N
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resumeButton.setBackground(new java.awt.Color(85, 88, 90));
        resumeButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        resumeButton.setForeground(new java.awt.Color(187, 187, 187));
        resumeButton.setText("RESUME");
        resumeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resumeButtonMouseClicked(evt);
            }
        });
        Panel.add(resumeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 110, 40));

        pauseButton.setBackground(new java.awt.Color(85, 88, 90));
        pauseButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        pauseButton.setForeground(new java.awt.Color(187, 187, 187));
        pauseButton.setText("PAUSE");
        pauseButton.setName(""); // NOI18N
        pauseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pauseButtonMouseClicked(evt);
            }
        });
        Panel.add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 110, 40));

        labelMadridAirport.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelMadridAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelMadridAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMadridAirport.setText("Madrid Airport");
        labelMadridAirport.setFocusable(false);
        labelMadridAirport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Panel.add(labelMadridAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 320, 40));

        labelBarcelonaAirport.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelBarcelonaAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelBarcelonaAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBarcelonaAirport.setText("Barcelona Airport");
        labelBarcelonaAirport.setFocusable(false);
        labelBarcelonaAirport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Panel.add(labelBarcelonaAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 320, 40));
        Panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1580, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setPreferredSize(new java.awt.Dimension(4, 0));
        Panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 80, 10, 640));

        labelBusTransfersAirportBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelBusTransfersAirportBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelBusTransfersAirportBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusTransfersAirportBarcelona.setText("Transfers Airport");
        labelBusTransfersAirportBarcelona.setFocusable(false);
        Panel.add(labelBusTransfersAirportBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 150, 150, 20));

        labelParkingAreaBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelParkingAreaBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelParkingAreaBarcelona.setText("Parking Area");
        labelParkingAreaBarcelona.setFocusable(false);
        Panel.add(labelParkingAreaBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));

        labelMaintenanceMadrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMaintenanceMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMaintenanceMadrid.setText("Maintenance");
        labelMaintenanceMadrid.setFocusable(false);
        Panel.add(labelMaintenanceMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 30));

        labelHangarMadrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelHangarMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelHangarMadrid.setText("Hangar");
        labelHangarMadrid.setFocusable(false);
        Panel.add(labelHangarMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 30));

        labelGate1Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate1Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate1Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate1Madrid.setText("Gate 1");
        labelGate1Madrid.setFocusable(false);
        Panel.add(labelGate1Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 70, 40));

        labelGate2Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate2Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate2Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate2Madrid.setText("Gate 2");
        labelGate2Madrid.setFocusable(false);
        Panel.add(labelGate2Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 70, 40));

        labelGate3Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate3Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate3Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate3Madrid.setText("Gate 3");
        labelGate3Madrid.setFocusable(false);
        Panel.add(labelGate3Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 70, 40));

        labelGate4Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Madrid.setText("Gate 4");
        labelGate4Madrid.setFocusable(false);
        Panel.add(labelGate4Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 70, 40));

        labelGate5Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate5Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate5Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate5Madrid.setText("Gate 5");
        labelGate5Madrid.setFocusable(false);
        Panel.add(labelGate5Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 70, 40));

        labelGate6Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate6Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate6Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate6Madrid.setText("Gate 6");
        labelGate6Madrid.setFocusable(false);
        Panel.add(labelGate6Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 70, 40));

        labelGate1Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate1Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate1Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate1Barcelona.setText("Gate 1");
        labelGate1Barcelona.setFocusable(false);
        Panel.add(labelGate1Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 70, 40));

        labelGate2Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate2Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate2Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate2Barcelona.setText("Gate 2");
        labelGate2Barcelona.setFocusable(false);
        Panel.add(labelGate2Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 70, 40));

        labelGate3Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate3Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate3Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate3Barcelona.setText("Gate 3");
        labelGate3Barcelona.setFocusable(false);
        Panel.add(labelGate3Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 70, 40));

        labelGate4Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Barcelona.setText("Gate 4");
        labelGate4Barcelona.setFocusable(false);
        Panel.add(labelGate4Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 400, 70, 40));

        labelGate5Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate5Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate5Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate5Barcelona.setText("Gate 5");
        labelGate5Barcelona.setFocusable(false);
        Panel.add(labelGate5Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 460, 70, 40));

        labelGate6Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate6Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate6Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate6Barcelona.setText("Gate 6");
        labelGate6Barcelona.setFocusable(false);
        Panel.add(labelGate6Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 520, 70, 40));

        updaterBusToDowntownBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updaterBusToDowntownBarcelona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterBusToDowntownBarcelona.setFocusable(false);
        Panel.add(updaterBusToDowntownBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 180, 110, 30));

        updaterBarcelonaCurrentPassengers.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterBarcelonaCurrentPassengers.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterBarcelonaCurrentPassengers.setToolTipText("");
        updaterBarcelonaCurrentPassengers.setFocusable(false);
        updaterBarcelonaCurrentPassengers.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Panel.add(updaterBarcelonaCurrentPassengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, 90, 30));

        updaterMadridCurrentPassengers.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        updaterMadridCurrentPassengers.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        updaterMadridCurrentPassengers.setToolTipText("");
        updaterMadridCurrentPassengers.setFocusable(false);
        updaterMadridCurrentPassengers.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Panel.add(updaterMadridCurrentPassengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, 30));

        labelNumberPassengersMadridAirport.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelNumberPassengersMadridAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersMadridAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersMadridAirport.setText("Airport Passengers");
        labelNumberPassengersMadridAirport.setFocusable(false);
        Panel.add(labelNumberPassengersMadridAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 30));

        labelNumberPassengersBarcelonaAirport.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelNumberPassengersBarcelonaAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersBarcelonaAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersBarcelonaAirport.setText("Airport Passengers");
        labelNumberPassengersBarcelonaAirport.setFocusable(false);
        Panel.add(labelNumberPassengersBarcelonaAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 180, 30));

        updaterGate6Madrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate6Madrid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate6Madrid.setFocusable(false);
        Panel.add(updaterGate6Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 290, 40));

        updaterGate5Madrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate5Madrid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate5Madrid.setFocusable(false);
        Panel.add(updaterGate5Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 290, 40));

        updaterGate4Madrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate4Madrid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate4Madrid.setFocusable(false);
        Panel.add(updaterGate4Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 290, 40));

        updaterGate3Madrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate3Madrid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate3Madrid.setFocusable(false);
        Panel.add(updaterGate3Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 290, 40));

        updaterGate2Madrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate2Madrid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate2Madrid.setFocusable(false);
        Panel.add(updaterGate2Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 290, 40));

        updaterGate1Madrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate1Madrid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate1Madrid.setFocusable(false);
        Panel.add(updaterGate1Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 290, 40));

        updaterGate1Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate1Barcelona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate1Barcelona.setFocusable(false);
        Panel.add(updaterGate1Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 290, 40));

        updaterGate2Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate2Barcelona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate2Barcelona.setFocusable(false);
        Panel.add(updaterGate2Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 290, 40));

        updaterGate3Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate3Barcelona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate3Barcelona.setFocusable(false);
        Panel.add(updaterGate3Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 290, 40));

        updaterGate4Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate4Barcelona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate4Barcelona.setFocusable(false);
        Panel.add(updaterGate4Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 400, 290, 40));

        updaterGate5Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate5Barcelona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate5Barcelona.setFocusable(false);
        Panel.add(updaterGate5Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 460, 290, 40));

        updaterGate6Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate6Barcelona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate6Barcelona.setFocusable(false);
        Panel.add(updaterGate6Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 520, 290, 40));

        labelBusTransfersDowntownBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelBusTransfersDowntownBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelBusTransfersDowntownBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusTransfersDowntownBarcelona.setText("Transfers Downtown");
        labelBusTransfersDowntownBarcelona.setFocusable(false);
        Panel.add(labelBusTransfersDowntownBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 150, 190, 20));

        updaterBusToAirportBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updaterBusToAirportBarcelona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterBusToAirportBarcelona.setFocusable(false);
        Panel.add(updaterBusToAirportBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 180, 110, 30));

        labelBusTransfersAirportMadrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelBusTransfersAirportMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelBusTransfersAirportMadrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusTransfersAirportMadrid.setText("Transfers Airport");
        labelBusTransfersAirportMadrid.setFocusable(false);
        Panel.add(labelBusTransfersAirportMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 150, 20));

        labelBusTransfersDowntownMadrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelBusTransfersDowntownMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelBusTransfersDowntownMadrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusTransfersDowntownMadrid.setText("Transfers Downtown");
        labelBusTransfersDowntownMadrid.setFocusable(false);
        Panel.add(labelBusTransfersDowntownMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 190, 20));

        updaterBusToAirportMadrid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updaterBusToAirportMadrid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterBusToAirportMadrid.setFocusable(false);
        Panel.add(updaterBusToAirportMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 110, 30));

        updaterBusToDowntownMadrid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updaterBusToDowntownMadrid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterBusToDowntownMadrid.setFocusable(false);
        Panel.add(updaterBusToDowntownMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 110, 30));

        updaterParkingAreaMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterParkingAreaMadrid.setAutoscrolls(false);
        updaterParkingAreaMadrid.setFocusable(false);
        Panel.add(updaterParkingAreaMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 630, 30));

        updaterHangarMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterHangarMadrid.setAutoscrolls(false);
        updaterHangarMadrid.setFocusable(false);
        Panel.add(updaterHangarMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 630, -1));

        updaterMaintenanceMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterMaintenanceMadrid.setAutoscrolls(false);
        updaterMaintenanceMadrid.setFocusable(false);
        Panel.add(updaterMaintenanceMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 630, 30));

        updaterParkingAreaBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterParkingAreaBarcelona.setAutoscrolls(false);
        updaterParkingAreaBarcelona.setFocusable(false);
        Panel.add(updaterParkingAreaBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, 630, 30));

        updaterMaintenanceBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterMaintenanceBarcelona.setAutoscrolls(false);
        updaterMaintenanceBarcelona.setFocusable(false);
        Panel.add(updaterMaintenanceBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 630, 30));

        labelMaintenanceMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMaintenanceMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMaintenanceMadrid1.setText("Maintenance");
        labelMaintenanceMadrid1.setFocusable(false);
        Panel.add(labelMaintenanceMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, -1, 30));

        labelParkingAreaBarcelona1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelParkingAreaBarcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaBarcelona1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelParkingAreaBarcelona1.setText("Parking Area");
        labelParkingAreaBarcelona1.setFocusable(false);
        Panel.add(labelParkingAreaBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, -1, 30));

        labelHangarMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelHangarMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelHangarMadrid1.setText("Hangar");
        labelHangarMadrid1.setFocusable(false);
        Panel.add(labelHangarMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 110, 30));

        updaterHangarBarcleona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterHangarBarcleona.setAutoscrolls(false);
        updaterHangarBarcleona.setFocusable(false);
        Panel.add(updaterHangarBarcleona, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 630, -1));

        labelTaxiMadrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTaxiMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiMadrid.setText("Taxi Area");
        labelTaxiMadrid.setFocusable(false);
        Panel.add(labelTaxiMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, 30));

        updaterTaxiMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterTaxiMadrid.setAutoscrolls(false);
        updaterTaxiMadrid.setFocusable(false);
        Panel.add(updaterTaxiMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 630, 30));

        labelTaxiBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTaxiBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTaxiBarcelona.setText("Taxi Area");
        labelTaxiBarcelona.setFocusable(false);
        Panel.add(labelTaxiBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, -1, 30));

        updaterTaxiBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterTaxiBarcelona.setAutoscrolls(false);
        updaterTaxiBarcelona.setFocusable(false);
        Panel.add(updaterTaxiBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, 630, 30));

        updaterAirwayBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterAirwayBarcelona.setAutoscrolls(false);
        updaterAirwayBarcelona.setFocusable(false);
        Panel.add(updaterAirwayBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, 1560, 30));

        updaterAirwayMadrid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updaterAirwayMadrid.setAutoscrolls(false);
        updaterAirwayMadrid.setFocusable(false);
        Panel.add(updaterAirwayMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, 1560, 30));

        labelTaxiMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTaxiMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid1.setText("Airway Barcelona - Madrid");
        labelTaxiMadrid1.setFocusable(false);
        Panel.add(labelTaxiMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, -1, 40));

        labelTaxiMadrid2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTaxiMadrid2.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiMadrid2.setText("Airway Madrid - Barcelona");
        labelTaxiMadrid2.setFocusable(false);
        Panel.add(labelTaxiMadrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, -1, 40));
        Panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 1560, 10));

        labelGate1Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate1Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate1Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate1Madrid1.setText("Runway 1");
        labelGate1Madrid1.setFocusable(false);
        Panel.add(labelGate1Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 100, 30));

        labelGate2Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate2Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate2Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate2Madrid1.setText("Runway 2");
        labelGate2Madrid1.setFocusable(false);
        Panel.add(labelGate2Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 100, 30));

        updaterGate2Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate2Madrid1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate2Madrid1.setFocusable(false);
        Panel.add(updaterGate2Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 680, 240, 30));

        labelGate4Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Madrid1.setText("Runway 4");
        labelGate4Madrid1.setFocusable(false);
        Panel.add(labelGate4Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, 100, 30));

        labelGate4Madrid2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Madrid2.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Madrid2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Madrid2.setText("Runway 3");
        labelGate4Madrid2.setFocusable(false);
        Panel.add(labelGate4Madrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 100, 30));

        updaterGate1Madrid2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate1Madrid2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate1Madrid2.setFocusable(false);
        Panel.add(updaterGate1Madrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, 240, 30));

        updaterGate1Madrid3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate1Madrid3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate1Madrid3.setFocusable(false);
        Panel.add(updaterGate1Madrid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 240, 30));

        updaterGate1Madrid4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate1Madrid4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate1Madrid4.setFocusable(false);
        Panel.add(updaterGate1Madrid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, 240, 30));

        labelGate1Madrid2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate1Madrid2.setForeground(new java.awt.Color(255, 255, 255));
        labelGate1Madrid2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate1Madrid2.setText("Runway 1");
        labelGate1Madrid2.setFocusable(false);
        Panel.add(labelGate1Madrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, 100, 30));

        labelGate2Madrid2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate2Madrid2.setForeground(new java.awt.Color(255, 255, 255));
        labelGate2Madrid2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate2Madrid2.setText("Runway 2");
        labelGate2Madrid2.setFocusable(false);
        Panel.add(labelGate2Madrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 100, 30));

        updaterGate2Madrid2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate2Madrid2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate2Madrid2.setFocusable(false);
        Panel.add(updaterGate2Madrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 680, 240, 30));

        labelGate4Madrid3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Madrid3.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Madrid3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Madrid3.setText("Runway 4");
        labelGate4Madrid3.setFocusable(false);
        Panel.add(labelGate4Madrid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 680, 100, 30));

        labelGate4Madrid4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Madrid4.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Madrid4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Madrid4.setText("Runway 3");
        labelGate4Madrid4.setFocusable(false);
        Panel.add(labelGate4Madrid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 640, 100, 30));

        updaterGate1Madrid5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate1Madrid5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate1Madrid5.setFocusable(false);
        Panel.add(updaterGate1Madrid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 680, 240, 30));

        updaterGate1Madrid6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate1Madrid6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate1Madrid6.setFocusable(false);
        Panel.add(updaterGate1Madrid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 640, 240, 30));

        updaterGate1Madrid7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updaterGate1Madrid7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        updaterGate1Madrid7.setFocusable(false);
        Panel.add(updaterGate1Madrid7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 640, 240, 30));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));
        Panel.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resumeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumeButtonMouseClicked
        pauseControl.resume();
        resumeUpdates();
        System.out.println("THREADS RESUMED.");
    }//GEN-LAST:event_resumeButtonMouseClicked

    private void pauseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMouseClicked
        pauseControl.pause();
        pauseUpdates();
        System.out.println("THREADS PAUSED.");
    }//GEN-LAST:event_pauseButtonMouseClicked

    public void startInterface() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Make the UserInterface visible.
                    setVisible(true);

                    // Perform periodic updates on the JLabel using SwingUtilities.invokeLater()
                    Timer timer = new Timer(25, e -> {
                        if (!isPaused()) {
                            updateInterface();
                        }
                    });

                    timer.start();
                    // Closes the program gracefully.
                    setDefaultCloseOperation(UserInterface.EXIT_ON_CLOSE);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Method to update the User Interface.
    public void updateInterface() {

        NumberFormat numberFormat = NumberFormat.getNumberInstance();

        // Update number of passengers currently at Madrid airport.
        String formattedNumber = numberFormat.format(madridAirport.getCurrentPassengers());
        updaterMadridCurrentPassengers.setText(formattedNumber);

        // Update number of passengers currently at Barcelona airport.
        formattedNumber = numberFormat.format(barcelonaAirport.getCurrentPassengers());
        updaterBarcelonaCurrentPassengers.setText(formattedNumber);

        // Update Gates 1-6 status at Madrid airport.
        for (int i = 0; i < 6; i++) {
            BoardingGate gate = madridAirport.getBoardingGates(i);

            String status = gate.getAirplaneStatus();
            switch (i) {
                case 0 ->
                    updaterGate1Madrid.setText(status);
                case 1 ->
                    updaterGate2Madrid.setText(status);
                case 2 ->
                    updaterGate3Madrid.setText(status);
                case 3 ->
                    updaterGate4Madrid.setText(status);
                case 4 ->
                    updaterGate5Madrid.setText(status);
                case 5 ->
                    updaterGate6Madrid.setText(status);
            }
        }

        // Update Gates 1-6 status at Madrid airport.
        for (int i = 0; i < 6; i++) {
            BoardingGate gate = barcelonaAirport.getBoardingGates(i);

            String status = gate.getAirplaneStatus();
            switch (i) {
                case 0 ->
                    updaterGate1Barcelona.setText(status);
                case 1 ->
                    updaterGate2Barcelona.setText(status);
                case 2 ->
                    updaterGate3Barcelona.setText(status);
                case 3 ->
                    updaterGate4Barcelona.setText(status);
                case 4 ->
                    updaterGate5Barcelona.setText(status);
                case 5 ->
                    updaterGate6Barcelona.setText(status);
            }
        }

        // Update Bus to Airport and Downtown statuses.
        updaterBusToAirportMadrid.setText(madridAirport.getStatusBusToAirport());
        updaterBusToDowntownMadrid.setText(madridAirport.getStatusBusToDowntown());

        updaterBusToAirportBarcelona.setText(barcelonaAirport.getStatusBusToAirport());
        updaterBusToDowntownBarcelona.setText(barcelonaAirport.getStatusBusToDowntown());

        // Update the hangars.
        updaterHangarMadrid.setText(madridAirport.getHangar().getStatus());
        updaterHangarBarcleona.setText(barcelonaAirport.getHangar().getStatus());
        /*
        // Update the maintenance halls.
        updaterMaintenanceMadrid.setText(madridAirport.getMaintenanceHall().getStatus());
        updaterMaintenanceBarcelona.setText(barcelonaAirport.getMaintenanceHall().getStatus());
         */
        // Update the parking areas.
        updaterParkingAreaMadrid.setText(madridAirport.getParkingArea().getStatus());
        updaterParkingAreaBarcelona.setText(barcelonaAirport.getParkingArea().getStatus());

    }

    public void setPaused(boolean paused) {
        this.isPaused = paused;
    }

    public boolean isPaused() {
        return this.isPaused;
    }

    public void pauseUpdates() {
        setPaused(true);
    }

    public void resumeUpdates() {
        setPaused(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelBarcelonaAirport;
    private javax.swing.JLabel labelBusTransfersAirportBarcelona;
    private javax.swing.JLabel labelBusTransfersAirportMadrid;
    private javax.swing.JLabel labelBusTransfersDowntownBarcelona;
    private javax.swing.JLabel labelBusTransfersDowntownMadrid;
    private javax.swing.JLabel labelGate1Barcelona;
    private javax.swing.JLabel labelGate1Madrid;
    private javax.swing.JLabel labelGate1Madrid1;
    private javax.swing.JLabel labelGate1Madrid2;
    private javax.swing.JLabel labelGate2Barcelona;
    private javax.swing.JLabel labelGate2Madrid;
    private javax.swing.JLabel labelGate2Madrid1;
    private javax.swing.JLabel labelGate2Madrid2;
    private javax.swing.JLabel labelGate3Barcelona;
    private javax.swing.JLabel labelGate3Madrid;
    private javax.swing.JLabel labelGate4Barcelona;
    private javax.swing.JLabel labelGate4Madrid;
    private javax.swing.JLabel labelGate4Madrid1;
    private javax.swing.JLabel labelGate4Madrid2;
    private javax.swing.JLabel labelGate4Madrid3;
    private javax.swing.JLabel labelGate4Madrid4;
    private javax.swing.JLabel labelGate5Barcelona;
    private javax.swing.JLabel labelGate5Madrid;
    private javax.swing.JLabel labelGate6Barcelona;
    private javax.swing.JLabel labelGate6Madrid;
    private javax.swing.JLabel labelHangarMadrid;
    private javax.swing.JLabel labelHangarMadrid1;
    private javax.swing.JLabel labelMadridAirport;
    private javax.swing.JLabel labelMaintenanceMadrid;
    private javax.swing.JLabel labelMaintenanceMadrid1;
    private javax.swing.JLabel labelNumberPassengersBarcelonaAirport;
    private javax.swing.JLabel labelNumberPassengersMadridAirport;
    private javax.swing.JLabel labelParkingAreaBarcelona;
    private javax.swing.JLabel labelParkingAreaBarcelona1;
    private javax.swing.JLabel labelTaxiBarcelona;
    private javax.swing.JLabel labelTaxiMadrid;
    private javax.swing.JLabel labelTaxiMadrid1;
    private javax.swing.JLabel labelTaxiMadrid2;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton resumeButton;
    private javax.swing.JTextField updaterAirwayBarcelona;
    private javax.swing.JTextField updaterAirwayMadrid;
    private javax.swing.JFormattedTextField updaterBarcelonaCurrentPassengers;
    private javax.swing.JTextField updaterBusToAirportBarcelona;
    private javax.swing.JTextField updaterBusToAirportMadrid;
    private javax.swing.JTextField updaterBusToDowntownBarcelona;
    private javax.swing.JTextField updaterBusToDowntownMadrid;
    private javax.swing.JTextField updaterGate1Barcelona;
    private javax.swing.JTextField updaterGate1Madrid;
    private javax.swing.JTextField updaterGate1Madrid2;
    private javax.swing.JTextField updaterGate1Madrid3;
    private javax.swing.JTextField updaterGate1Madrid4;
    private javax.swing.JTextField updaterGate1Madrid5;
    private javax.swing.JTextField updaterGate1Madrid6;
    private javax.swing.JTextField updaterGate1Madrid7;
    private javax.swing.JTextField updaterGate2Barcelona;
    private javax.swing.JTextField updaterGate2Madrid;
    private javax.swing.JTextField updaterGate2Madrid1;
    private javax.swing.JTextField updaterGate2Madrid2;
    private javax.swing.JTextField updaterGate3Barcelona;
    private javax.swing.JTextField updaterGate3Madrid;
    private javax.swing.JTextField updaterGate4Barcelona;
    private javax.swing.JTextField updaterGate4Madrid;
    private javax.swing.JTextField updaterGate5Barcelona;
    private javax.swing.JTextField updaterGate5Madrid;
    private javax.swing.JTextField updaterGate6Barcelona;
    private javax.swing.JTextField updaterGate6Madrid;
    private javax.swing.JTextField updaterHangarBarcleona;
    private javax.swing.JTextField updaterHangarMadrid;
    private javax.swing.JFormattedTextField updaterMadridCurrentPassengers;
    private javax.swing.JTextField updaterMaintenanceBarcelona;
    private javax.swing.JTextField updaterMaintenanceMadrid;
    private javax.swing.JTextField updaterParkingAreaBarcelona;
    private javax.swing.JTextField updaterParkingAreaMadrid;
    private javax.swing.JTextField updaterTaxiBarcelona;
    private javax.swing.JTextField updaterTaxiMadrid;
    // End of variables declaration//GEN-END:variables
}
