package com.catl.ui;

public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pauseButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelMadridAirport = new javax.swing.JLabel();
        labelBarcelonaAirport = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelTaxiAreaMadrid = new javax.swing.JLabel();
        labelParkingAreaMadrid = new javax.swing.JLabel();
        labelParkingAreaBarcelona = new javax.swing.JLabel();
        labelMaintenanceBarcelona = new javax.swing.JLabel();
        labelMaintenanceMadrid = new javax.swing.JLabel();
        labelHangarBarcelona = new javax.swing.JLabel();
        labelHangarMadrid = new javax.swing.JLabel();
        labelNumberPassengersMadridAirport = new javax.swing.JLabel();
        labelNumberPassengersBarcelonaAirport = new javax.swing.JLabel();
        labelGate1Madrid = new javax.swing.JLabel();
        labelGate2Madrid = new javax.swing.JLabel();
        labelGate3Madrid = new javax.swing.JLabel();
        labelGate4Madrid = new javax.swing.JLabel();
        labelGate5Madrid = new javax.swing.JLabel();
        labelGate6Madrid = new javax.swing.JLabel();
        labelGate1Barcelona = new javax.swing.JLabel();
        labelGate2Barcelona = new javax.swing.JLabel();
        labelGate3Barcelona = new javax.swing.JLabel();
        labelGate4Barcelona = new javax.swing.JLabel();
        labelGate5Barcelona = new javax.swing.JLabel();
        labelGate6Barcelona = new javax.swing.JLabel();
        labelTaxiAreaBarcelona = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pauseButton1 = new javax.swing.JButton();
        resumeButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        labelMadridAirport1 = new javax.swing.JLabel();
        labelBarcelonaAirport1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        labelTaxiAreaMadrid1 = new javax.swing.JLabel();
        labelParkingAreaMadrid1 = new javax.swing.JLabel();
        labelParkingAreaBarcelona1 = new javax.swing.JLabel();
        labelMaintenanceBarcelona1 = new javax.swing.JLabel();
        labelMaintenanceMadrid1 = new javax.swing.JLabel();
        labelHangarBarcelona1 = new javax.swing.JLabel();
        labelHangarMadrid1 = new javax.swing.JLabel();
        labelNumberPassengersMadridAirport1 = new javax.swing.JLabel();
        labelNumberPassengersBarcelonaAirport1 = new javax.swing.JLabel();
        labelGate1Madrid1 = new javax.swing.JLabel();
        labelGate2Madrid1 = new javax.swing.JLabel();
        labelGate3Madrid1 = new javax.swing.JLabel();
        labelGate4Madrid1 = new javax.swing.JLabel();
        labelGate5Madrid1 = new javax.swing.JLabel();
        labelGate6Madrid1 = new javax.swing.JLabel();
        labelGate1Barcelona1 = new javax.swing.JLabel();
        labelGate2Barcelona1 = new javax.swing.JLabel();
        labelGate3Barcelona1 = new javax.swing.JLabel();
        labelGate4Barcelona1 = new javax.swing.JLabel();
        labelGate5Barcelona1 = new javax.swing.JLabel();
        labelGate6Barcelona1 = new javax.swing.JLabel();
        labelTaxiAreaBarcelona1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1600, 1000));
        setPreferredSize(new java.awt.Dimension(1600, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(60, 63, 65));
        jPanel1.setName("Airport Simulator"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pauseButton.setBackground(new java.awt.Color(85, 88, 90));
        pauseButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        pauseButton.setForeground(new java.awt.Color(187, 187, 187));
        pauseButton.setText("PAUSE");
        pauseButton.setName(""); // NOI18N
        jPanel1.add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 110, 40));

        resumeButton.setBackground(new java.awt.Color(85, 88, 90));
        resumeButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        resumeButton.setForeground(new java.awt.Color(187, 187, 187));
        resumeButton.setText("RESUME");
        jPanel1.add(resumeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 110, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1580, 10));

        labelMadridAirport.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelMadridAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelMadridAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMadridAirport.setText("Madrid Airport");
        labelMadridAirport.setFocusable(false);
        labelMadridAirport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(labelMadridAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 320, 40));

        labelBarcelonaAirport.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelBarcelonaAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelBarcelonaAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBarcelonaAirport.setText("Barcelona Airport");
        labelBarcelonaAirport.setFocusable(false);
        labelBarcelonaAirport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(labelBarcelonaAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 320, 40));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 10, 900));

        labelTaxiAreaMadrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelTaxiAreaMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiAreaMadrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTaxiAreaMadrid.setText("Taxi Area");
        labelTaxiAreaMadrid.setFocusable(false);
        jPanel1.add(labelTaxiAreaMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 130, 30));

        labelParkingAreaMadrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelParkingAreaMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaMadrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelParkingAreaMadrid.setText("Parking Area");
        labelParkingAreaMadrid.setFocusable(false);
        jPanel1.add(labelParkingAreaMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 130, 30));

        labelParkingAreaBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelParkingAreaBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelParkingAreaBarcelona.setText("Parking Area");
        labelParkingAreaBarcelona.setFocusable(false);
        jPanel1.add(labelParkingAreaBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 30));

        labelMaintenanceBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelMaintenanceBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaintenanceBarcelona.setText("Maintenance");
        labelMaintenanceBarcelona.setFocusable(false);
        jPanel1.add(labelMaintenanceBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 130, 30));

        labelMaintenanceMadrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelMaintenanceMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceMadrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaintenanceMadrid.setText("Maintenance");
        labelMaintenanceMadrid.setFocusable(false);
        jPanel1.add(labelMaintenanceMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, 30));

        labelHangarBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelHangarBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHangarBarcelona.setText("Hangar");
        labelHangarBarcelona.setFocusable(false);
        jPanel1.add(labelHangarBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 70, 30));

        labelHangarMadrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelHangarMadrid.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarMadrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHangarMadrid.setText("Hangar");
        labelHangarMadrid.setFocusable(false);
        jPanel1.add(labelHangarMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 70, 30));

        labelNumberPassengersMadridAirport.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelNumberPassengersMadridAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersMadridAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersMadridAirport.setText("Numbers of Passengers at the Airport");
        labelNumberPassengersMadridAirport.setFocusable(false);
        jPanel1.add(labelNumberPassengersMadridAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 360, 30));

        labelNumberPassengersBarcelonaAirport.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelNumberPassengersBarcelonaAirport.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersBarcelonaAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersBarcelonaAirport.setText("Numbers of Passengers at the Airport");
        labelNumberPassengersBarcelonaAirport.setFocusable(false);
        jPanel1.add(labelNumberPassengersBarcelonaAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 360, 30));

        labelGate1Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate1Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate1Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate1Madrid.setText("Gate 1");
        labelGate1Madrid.setFocusable(false);
        jPanel1.add(labelGate1Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 130, 30));

        labelGate2Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate2Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate2Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate2Madrid.setText("Gate 2");
        labelGate2Madrid.setFocusable(false);
        jPanel1.add(labelGate2Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 130, 30));

        labelGate3Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate3Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate3Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate3Madrid.setText("Gate 3");
        labelGate3Madrid.setFocusable(false);
        jPanel1.add(labelGate3Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 130, 30));

        labelGate4Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Madrid.setText("Gate 4");
        labelGate4Madrid.setFocusable(false);
        jPanel1.add(labelGate4Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 130, 30));

        labelGate5Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate5Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate5Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate5Madrid.setText("Gate 5");
        labelGate5Madrid.setFocusable(false);
        jPanel1.add(labelGate5Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 130, 30));

        labelGate6Madrid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate6Madrid.setForeground(new java.awt.Color(255, 255, 255));
        labelGate6Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate6Madrid.setText("Gate 6");
        labelGate6Madrid.setFocusable(false);
        jPanel1.add(labelGate6Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 130, 30));

        labelGate1Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate1Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate1Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate1Barcelona.setText("Gate 1");
        labelGate1Barcelona.setFocusable(false);
        jPanel1.add(labelGate1Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 130, 30));

        labelGate2Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate2Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate2Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate2Barcelona.setText("Gate 2");
        labelGate2Barcelona.setFocusable(false);
        jPanel1.add(labelGate2Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 130, 30));

        labelGate3Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate3Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate3Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate3Barcelona.setText("Gate 3");
        labelGate3Barcelona.setFocusable(false);
        jPanel1.add(labelGate3Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 130, 30));

        labelGate4Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Barcelona.setText("Gate 4");
        labelGate4Barcelona.setFocusable(false);
        jPanel1.add(labelGate4Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 420, 130, 30));

        labelGate5Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate5Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate5Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate5Barcelona.setText("Gate 5");
        labelGate5Barcelona.setFocusable(false);
        jPanel1.add(labelGate5Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 450, 130, 30));

        labelGate6Barcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate6Barcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelGate6Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate6Barcelona.setText("Gate 6");
        labelGate6Barcelona.setFocusable(false);
        jPanel1.add(labelGate6Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 480, 130, 30));

        labelTaxiAreaBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelTaxiAreaBarcelona.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiAreaBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTaxiAreaBarcelona.setText("Taxi Area");
        labelTaxiAreaBarcelona.setFocusable(false);
        jPanel1.add(labelTaxiAreaBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 130, 30));

        jPanel2.setBackground(new java.awt.Color(60, 63, 65));
        jPanel2.setName("Airport Simulator"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1600, 1000));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pauseButton1.setBackground(new java.awt.Color(85, 88, 90));
        pauseButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        pauseButton1.setForeground(new java.awt.Color(187, 187, 187));
        pauseButton1.setText("PAUSE");
        pauseButton1.setName(""); // NOI18N
        jPanel2.add(pauseButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 110, 40));

        resumeButton1.setBackground(new java.awt.Color(85, 88, 90));
        resumeButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        resumeButton1.setForeground(new java.awt.Color(187, 187, 187));
        resumeButton1.setText("RESUME");
        jPanel2.add(resumeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 110, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1580, 10));

        labelMadridAirport1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelMadridAirport1.setForeground(new java.awt.Color(255, 255, 255));
        labelMadridAirport1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMadridAirport1.setText("Madrid Airport");
        labelMadridAirport1.setFocusable(false);
        labelMadridAirport1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel2.add(labelMadridAirport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 320, 40));

        labelBarcelonaAirport1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        labelBarcelonaAirport1.setForeground(new java.awt.Color(255, 255, 255));
        labelBarcelonaAirport1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBarcelonaAirport1.setText("Barcelona Airport");
        labelBarcelonaAirport1.setFocusable(false);
        labelBarcelonaAirport1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel2.add(labelBarcelonaAirport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 320, 40));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 10, 900));

        labelTaxiAreaMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelTaxiAreaMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiAreaMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTaxiAreaMadrid1.setText("Taxi Area");
        labelTaxiAreaMadrid1.setFocusable(false);
        jPanel2.add(labelTaxiAreaMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 130, 30));

        labelParkingAreaMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelParkingAreaMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelParkingAreaMadrid1.setText("Parking Area");
        labelParkingAreaMadrid1.setFocusable(false);
        jPanel2.add(labelParkingAreaMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 130, 30));

        labelParkingAreaBarcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelParkingAreaBarcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelParkingAreaBarcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelParkingAreaBarcelona1.setText("Parking Area");
        labelParkingAreaBarcelona1.setFocusable(false);
        jPanel2.add(labelParkingAreaBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 30));

        labelMaintenanceBarcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelMaintenanceBarcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceBarcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaintenanceBarcelona1.setText("Maintenance");
        labelMaintenanceBarcelona1.setFocusable(false);
        jPanel2.add(labelMaintenanceBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 130, 30));

        labelMaintenanceMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelMaintenanceMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelMaintenanceMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaintenanceMadrid1.setText("Maintenance");
        labelMaintenanceMadrid1.setFocusable(false);
        jPanel2.add(labelMaintenanceMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, 30));

        labelHangarBarcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelHangarBarcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarBarcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHangarBarcelona1.setText("Hangar");
        labelHangarBarcelona1.setFocusable(false);
        jPanel2.add(labelHangarBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 70, 30));

        labelHangarMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelHangarMadrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelHangarMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHangarMadrid1.setText("Hangar");
        labelHangarMadrid1.setFocusable(false);
        jPanel2.add(labelHangarMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 70, 30));

        labelNumberPassengersMadridAirport1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelNumberPassengersMadridAirport1.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersMadridAirport1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersMadridAirport1.setText("Numbers of Passengers at the Airport");
        labelNumberPassengersMadridAirport1.setFocusable(false);
        jPanel2.add(labelNumberPassengersMadridAirport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 360, 30));

        labelNumberPassengersBarcelonaAirport1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelNumberPassengersBarcelonaAirport1.setForeground(new java.awt.Color(255, 255, 255));
        labelNumberPassengersBarcelonaAirport1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumberPassengersBarcelonaAirport1.setText("Numbers of Passengers at the Airport");
        labelNumberPassengersBarcelonaAirport1.setFocusable(false);
        jPanel2.add(labelNumberPassengersBarcelonaAirport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 360, 30));

        labelGate1Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate1Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate1Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate1Madrid1.setText("Gate 1");
        labelGate1Madrid1.setFocusable(false);
        jPanel2.add(labelGate1Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 130, 30));

        labelGate2Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate2Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate2Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate2Madrid1.setText("Gate 2");
        labelGate2Madrid1.setFocusable(false);
        jPanel2.add(labelGate2Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 130, 30));

        labelGate3Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate3Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate3Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate3Madrid1.setText("Gate 3");
        labelGate3Madrid1.setFocusable(false);
        jPanel2.add(labelGate3Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 130, 30));

        labelGate4Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Madrid1.setText("Gate 4");
        labelGate4Madrid1.setFocusable(false);
        jPanel2.add(labelGate4Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 130, 30));

        labelGate5Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate5Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate5Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate5Madrid1.setText("Gate 5");
        labelGate5Madrid1.setFocusable(false);
        jPanel2.add(labelGate5Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 130, 30));

        labelGate6Madrid1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate6Madrid1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate6Madrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate6Madrid1.setText("Gate 6");
        labelGate6Madrid1.setFocusable(false);
        jPanel2.add(labelGate6Madrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 130, 30));

        labelGate1Barcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate1Barcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate1Barcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate1Barcelona1.setText("Gate 1");
        labelGate1Barcelona1.setFocusable(false);
        jPanel2.add(labelGate1Barcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 130, 30));

        labelGate2Barcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate2Barcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate2Barcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate2Barcelona1.setText("Gate 2");
        labelGate2Barcelona1.setFocusable(false);
        jPanel2.add(labelGate2Barcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 130, 30));

        labelGate3Barcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate3Barcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate3Barcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate3Barcelona1.setText("Gate 3");
        labelGate3Barcelona1.setFocusable(false);
        jPanel2.add(labelGate3Barcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 130, 30));

        labelGate4Barcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate4Barcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate4Barcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate4Barcelona1.setText("Gate 4");
        labelGate4Barcelona1.setFocusable(false);
        jPanel2.add(labelGate4Barcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 420, 130, 30));

        labelGate5Barcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate5Barcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate5Barcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate5Barcelona1.setText("Gate 5");
        labelGate5Barcelona1.setFocusable(false);
        jPanel2.add(labelGate5Barcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 450, 130, 30));

        labelGate6Barcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelGate6Barcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelGate6Barcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGate6Barcelona1.setText("Gate 6");
        labelGate6Barcelona1.setFocusable(false);
        jPanel2.add(labelGate6Barcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 480, 130, 30));

        labelTaxiAreaBarcelona1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelTaxiAreaBarcelona1.setForeground(new java.awt.Color(255, 255, 255));
        labelTaxiAreaBarcelona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTaxiAreaBarcelona1.setText("Taxi Area");
        labelTaxiAreaBarcelona1.setFocusable(false);
        jPanel2.add(labelTaxiAreaBarcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 1000));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 1000));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf dark look and feel */
        try {
            // Set FlatLaf Cupertino Dark theme
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());

            // If you want to set the theme globally for all components, you can use:
            // FlatDarkLaf.setup();

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelBarcelonaAirport;
    private javax.swing.JLabel labelBarcelonaAirport1;
    private javax.swing.JLabel labelGate1Barcelona;
    private javax.swing.JLabel labelGate1Barcelona1;
    private javax.swing.JLabel labelGate1Madrid;
    private javax.swing.JLabel labelGate1Madrid1;
    private javax.swing.JLabel labelGate2Barcelona;
    private javax.swing.JLabel labelGate2Barcelona1;
    private javax.swing.JLabel labelGate2Madrid;
    private javax.swing.JLabel labelGate2Madrid1;
    private javax.swing.JLabel labelGate3Barcelona;
    private javax.swing.JLabel labelGate3Barcelona1;
    private javax.swing.JLabel labelGate3Madrid;
    private javax.swing.JLabel labelGate3Madrid1;
    private javax.swing.JLabel labelGate4Barcelona;
    private javax.swing.JLabel labelGate4Barcelona1;
    private javax.swing.JLabel labelGate4Madrid;
    private javax.swing.JLabel labelGate4Madrid1;
    private javax.swing.JLabel labelGate5Barcelona;
    private javax.swing.JLabel labelGate5Barcelona1;
    private javax.swing.JLabel labelGate5Madrid;
    private javax.swing.JLabel labelGate5Madrid1;
    private javax.swing.JLabel labelGate6Barcelona;
    private javax.swing.JLabel labelGate6Barcelona1;
    private javax.swing.JLabel labelGate6Madrid;
    private javax.swing.JLabel labelGate6Madrid1;
    private javax.swing.JLabel labelHangarBarcelona;
    private javax.swing.JLabel labelHangarBarcelona1;
    private javax.swing.JLabel labelHangarMadrid;
    private javax.swing.JLabel labelHangarMadrid1;
    private javax.swing.JLabel labelMadridAirport;
    private javax.swing.JLabel labelMadridAirport1;
    private javax.swing.JLabel labelMaintenanceBarcelona;
    private javax.swing.JLabel labelMaintenanceBarcelona1;
    private javax.swing.JLabel labelMaintenanceMadrid;
    private javax.swing.JLabel labelMaintenanceMadrid1;
    private javax.swing.JLabel labelNumberPassengersBarcelonaAirport;
    private javax.swing.JLabel labelNumberPassengersBarcelonaAirport1;
    private javax.swing.JLabel labelNumberPassengersMadridAirport;
    private javax.swing.JLabel labelNumberPassengersMadridAirport1;
    private javax.swing.JLabel labelParkingAreaBarcelona;
    private javax.swing.JLabel labelParkingAreaBarcelona1;
    private javax.swing.JLabel labelParkingAreaMadrid;
    private javax.swing.JLabel labelParkingAreaMadrid1;
    private javax.swing.JLabel labelTaxiAreaBarcelona;
    private javax.swing.JLabel labelTaxiAreaBarcelona1;
    private javax.swing.JLabel labelTaxiAreaMadrid;
    private javax.swing.JLabel labelTaxiAreaMadrid1;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton pauseButton1;
    private javax.swing.JButton resumeButton;
    private javax.swing.JButton resumeButton1;
    // End of variables declaration//GEN-END:variables
}
